### PR TITLE
Issue 345 blog

### PR DESCRIPTION
**Pull request by CristianGomezO**
New design in blog section

### CODE REVIEW

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO: looking ok, but medium.com rejected the connection:
Bildschirmfoto 2021-12-07 um 10 59 25
Can this be resolved?

**Comment by CristianGomezO** [comment]
@ReinhardSchmidt i think that is because the project is running local

**Comment by ReinhardSchmidt** [comment]
1. On this URL: https://hoprnet-org-v2-git-issue-345-blog-hoprnet.vercel.app, which is public it doesn‘t work, do you know why? 
2. If it does only work on Hoprnet.org. can you hide this by default so when can test it in production.

Just to avoid issues when deploying.

**Comment by CristianGomezO** [comment]
@ReinhardSchmidt medium rejects the connection, then it could not be resolved

Error

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO Ok in that case we have to alter the approach. Can you look into for ex. https://medium.datadriveninvestor.com/embed-medium-as-a-blog-on-your-site-54a1b49cbe16
or similar tutorials?

Functions we want:
- A header image of the latest article, in a two-column-layout. Very similar as on https://medium.com/hoprnet
- A category-function:
Bildschirmfoto 2021-12-10 um 11 21 54
- A lead/start of the actual article-text
- pereferably set in our Source Code Pro

And as a sidenote, we already do feature a simple medium-articlestream on https://hoprnet.org/de/blog, is this of any help? That one has no leads, is less nicely.

If you like to have a call, I am available on every day.

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO did my message help in one way or the other? Could you work on it within this week?

**Comment by ReinhardSchmidt** [comment]
please cut this frame:
Bildschirmfoto 2021-12-14 um 23 01 16

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO: many thanks, that worked.
- 1. Can you HOPR Hunt to: https://medium.com/hoprhunt
- 2. Work on the mobile-ver.: (A.) remove all strange image stretches of the main image, the profile pic. (B.) display the content only in one column and not three.
- HOPR BLOG and HOPR Hunt in the "grey bar", set in the same typesize as the menue, currently bigger
- The preview-images look somehow more pixelated than the need to be
- Menue-text and all Blog-Preview txt in HEX RGB: 414141

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO could you please find the time to look into it. We need to launch it very soon. Much appreciated.

**Comment by CristianGomezO** [comment]
@ReinhardSchmidt I'm already working on it

**Comment by ReinhardSchmidt** [comment]
@CristianGomezO Looking good! When clicking on "HOPR HUNT" please mirror the layout of the "HOPR BLOG" and crawl the content from "https://medium.com/hoprhunt". So no newtab that links to "https://medium.com/hoprhunt".

**Comment by ReinhardSchmidt** [comment]
- It looks like that the max. amount of displayed articles is limited to 7: one in the form of an hero and six regular tiles. Could you add a more button? 
- Could you shift the HOPR BLOG and HOPR HUNT more to the inside, on big screens they look displaced, way too much on the outside.
After that, we‘ll soon launch

**Review by ReinhardSchmidt — APPROVED** [review]

**Pull request merged**
